import Head from 'next/head'
import Banner from '@/components/Banner'
import BestSelling from '@/components/BestSelling'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Banner/>
        <BestSelling/>
        
      </main>
    </>
  )
}
